repos:
  - repo: https://github.com/golangci/golangci-lint
    rev: v1.57.2 # Use the latest golangci-lint version
    hooks:
      - id: golangci-lint
  - repo: local
    hooks:
      - id: gofmt
        name: gofmt
        entry: gofmt -w
        language: system
        types: [go]
